import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import localFont from 'next/font/local'

import "./globals.css";

const rockswellStd = localFont({ src: './fonts/RockwellStd.otf', variable: '--rockwell-std', display: 'swap' })

const plexMono = IBM_Plex_Mono({
  weight: "700",
  subsets: ['latin'],
  variable: '--plex-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rockswellStd.variable} ${plexMono.variable}`}>{children}</body>
    </html>
  );
}
